language: node_js
node_js:
- lts/*
script:
- npm run test
services:
- mongodb
deploy:
  provider: heroku
  app: sain20-arc
  api_key:
    secure: jF3HY9YvkYhxSGMcZz+T4E2rHTeJl6YP1WTe1nvwpNT5+bF9TU8jZY54CDpcN5rBYZ+u7bTUqas6TsJ5FhM/XF3+Eb/lHUKjBGeoyGrEst/Ndwijt0C6rsOxOCUvNPn+mjbZiMkQ6fv8EwTqg1kNBCdFuKHZD5vNC39AaNt2XpWvQvqmqBJpIwytRJqjxe7kRo8aecPLk0SOidwC8LWhMLBLKc+XXeZejoP6ottJtv6X+vINavxEpocdy2/2lCFGBEFcFJ4NqAH5dyaUJ30fKdDPFiQKH9n1GS61YBFRKuEDu0cvdL3PuQA5wn8a4j+OPpK0eomWdI4uwOQe/X3fghdFqB48mIUkKtLsSBfwAvmJDfazwCNvwfWmwqLswTBTYqJgombH9Ru/qlJpsq3dQk3OBfqhi7VoAhRxISItk8+G2ciSyT7e7aqAKX6hiFAVCJa/yckGOPKX2hbm5y3MNGv8f9KRSLx4DmCcgMnbdimZ1KDPqK+4RNKFG6uLXB2jNf6c3wVBFvaic+gYGw/ZaW08/VfB6Jfbs1YR5wDsqIzttR79oIKvFkLA0iI3hgHKt5FNhJ33QlZWyMdRXS2iFnLZcar6+Jd2BtUxZQ5xpS/gKt0rNwFrdmrXXZFhIk/OOqxunGcnUtc8Wn+5lSuNyufLWQhfs4NUDMvaoC/osSg=
branches:
  only:
  - master
